/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Offer } from "./offer";
import { Expose, Type } from "class-transformer";

/**
 * The offers related to the application with the given identifier were retrieved.
 */
export class ApplicationsOffersPaginated extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Offer })
    @Expose({ name: "data" })
    @Type(() => Offer)
    data: Offer[];

    @SpeakeasyMetadata()
    @Expose({ name: "next_page" })
    nextPage: string;

    @SpeakeasyMetadata()
    @Expose({ name: "raw" })
    raw?: string;
}
