/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Campaign } from "./campaign";
import { Expose, Type } from "class-transformer";

/**
 * The campaign with the given identifier was retrieved.
 */
export class CampaignResult extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => Campaign)
    data: Campaign;

    @SpeakeasyMetadata()
    @Expose({ name: "raw" })
    raw?: string;
}
