/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class CrmUpdateContactRequestDto extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "account_ids" })
    accountIds?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "company_name" })
    companyName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "deal_ids" })
    dealIds?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "emails" })
    emails?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "first_name" })
    firstName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_name" })
    lastName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "phone_numbers" })
    phoneNumbers?: string[];
}
