/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { EmploymentTypeEnum } from "./employmenttypeenum";
import { PayFrequencyEnum } from "./payfrequencyenum";
import { PayPeriodEnum } from "./payperiodenum";
import { Expose, Transform, Type } from "class-transformer";

export class Employment extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "effective_date" })
    @Transform(({ value }) => new Date(value), { toClassOnly: true })
    effectiveDate?: Date;

    @SpeakeasyMetadata()
    @Expose({ name: "employee_id" })
    employeeId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "employment_type" })
    @Type(() => EmploymentTypeEnum)
    employmentType?: EmploymentTypeEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "job_title" })
    jobTitle?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "pay_currency" })
    payCurrency?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "pay_frequency" })
    @Type(() => PayFrequencyEnum)
    payFrequency?: PayFrequencyEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "pay_period" })
    @Type(() => PayPeriodEnum)
    payPeriod?: PayPeriodEnum;

    @SpeakeasyMetadata()
    @Expose({ name: "pay_rate" })
    payRate?: string;
}
