/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Job } from "./job";
import { Expose, Type } from "class-transformer";

/**
 * The job with the given identifier was retrieved.
 */
export class JobResult extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "job" })
    @Type(() => Job)
    job: Job;

    @SpeakeasyMetadata()
    @Expose({ name: "raw" })
    raw?: string;
}
