/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Location } from "./location";
import { Expose, Type } from "class-transformer";

/**
 * The list of locations was retrieved.
 */
export class LocationsPaginated extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Location })
    @Expose({ name: "data" })
    @Type(() => Location)
    data: Location[];

    @SpeakeasyMetadata()
    @Expose({ name: "next_page" })
    nextPage: string;

    @SpeakeasyMetadata()
    @Expose({ name: "raw" })
    raw?: string;
}
