/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Location } from "./location";
import { Expose, Type } from "class-transformer";

/**
 * The location with the given identifier was retrieved.
 */
export class LocationResult extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    @Type(() => Location)
    data: Location;

    @SpeakeasyMetadata()
    @Expose({ name: "raw" })
    raw?: string;
}
