/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose } from "class-transformer";

export class SmsMessageContents extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "body" })
    body: string;

    @SpeakeasyMetadata()
    @Expose({ name: "from" })
    from?: string;
}
