/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Template } from "./template";
import { Expose, Type } from "class-transformer";

/**
 * The list of email templates was retrieved.
 */
export class TemplatesPaginated extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: Template })
    @Expose({ name: "data" })
    @Type(() => Template)
    data: Template[];

    @SpeakeasyMetadata()
    @Expose({ name: "next_page" })
    nextPage: string;

    @SpeakeasyMetadata()
    @Expose({ name: "raw" })
    raw?: string;
}
