/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { Candidates } from "./candidates";
import { SDKConfiguration } from "./sdk";

export class Ats {
    public candidates: Candidates;
    private sdkConfiguration: SDKConfiguration;

    constructor(sdkConfig: SDKConfiguration) {
        this.sdkConfiguration = sdkConfig;
        this.candidates = new Candidates(this.sdkConfiguration);
    }
}
